In [20]:
import tensorflow as tf
import keras
from keras.models import Sequential
import tensorflow.keras.layers as layers
import numpy as np

In [33]:
model = tf.keras.models.Sequential([
  tf.keras.layers.UpSampling2D()
])

#keras.layers.


In [39]:
# define input data
X = numpy.asarray([255,255,255])
print(X)

[255 255 255]


In [38]:
# # reshape input data into one sample a sample with a channel
# X = X.reshape((1, 2, 2, 1))

In [76]:
from keras.models import Sequential
from keras.layers import UpSampling2D
import numpy as np
# define model
model = Sequential()
model.add(UpSampling2D())
# example of using bilinear interpolation when upsampling
#model.add(UpSampling2D(interpolation='bilinear'))

#making the padding of the upsampling 2row x 3col
#model.add(UpSampling2D(size=(2, 3)))

# define input data
X = np.asarray([[1, 2],
			 [3, 4]])
# show input data for context
print("This is input: ", X)
# reshape input data into one sample a sample with a channel (grey scale)
X = X.reshape((1, 2, 2, 1))

# make a prediction with the model
yhat = model.predict(X)
# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 4))
# summarize output
print(yhat)
model.summary()


This is input:  [[1 2]
 [3 4]]
[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]
Model: "sequential_38"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_16 (UpSampling (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [78]:
from keras.models import Sequential
from keras.layers import UpSampling2D
from keras.layers import Conv2D
import numpy as np

#define model
model = Sequential()
model.add(Conv2D(1, (3,3), padding='same'))


# define input data
X = np.asarray([[1, 2],
			 [3, 4]])
# make a prediction with the model
yhat = model.predict(X)
print(yhat)
model.summary()

ValueError: Input 0 is incompatible with layer conv2d_4: expected ndim=4, found ndim=2

In [84]:
from keras.layers import Conv2D, Input
from keras.models import Model
import numpy as np
#https://qiita.com/koshian2/items/885aba771190267a3a1c
def normal_conv_two():
    input = Input((3,3,2))
    layer = Conv2D(3, kernel_size=3, use_bias=False) # 計算を簡単にするためにバイアス項を抜く
    x = layer(input)
    model = Model(input, x)

    weights = layer.get_weights()
    print(weights)
    print(weights[0].shape)#(3,3,2,3)

    weights = np.arange(1, 55).reshape(3,3,2,3).astype(np.float32)
    layer.set_weights([weights])

    print("weights")
    print(weights[:,:,0,0])
    print(weights[:,:,0,1])
    print(weights[:,:,0,2])
    print(weights[:,:,1,0])
    print(weights[:,:,1,1])
    print(weights[:,:,1,2])
    #one array of 3colx3rowx2col arrays
    X = np.arange(1, 19).reshape(1,3,3,2) * 0.1
    print("input")
    #print the first array (there is only one
    print(X)
    print(X[0,:,:,0])
    print(X[0,:,:,1])
    #print(X[0,:,:,2])

    result = model.predict(X)
    print("output")
    print(result[0,:,:,0]) # weights[:,:,0,0]*X[0,:,:,0] + weights[:,:,1,0]*X[0,:,:,1]
    print(result[0,:,:,1]) # weights[:,:,0,1]*X[0,:,:,0] + weights[:,:,1,1]*X[0,:,:,1]
    print(result[0,:,:,2]) # weights[:,:,0,2]*X[0,:,:,0] + weights[:,:,1,2]*X[0,:,:,1]

normal_conv_two()

[array([[[[ 0.0215959 ,  0.28967667, -0.30323923],
         [ 0.05953708,  0.16359001, -0.09093112]],

        [[-0.00792664, -0.31956393,  0.02068877],
         [ 0.34571618,  0.20450336,  0.19831192]],

        [[-0.25506115, -0.05476716, -0.16736722],
         [ 0.10322878,  0.06934375, -0.18719122]]],


       [[[ 0.17852259,  0.03203627, -0.06218311],
         [-0.01428354, -0.22615184, -0.06082657]],

        [[ 0.22778964,  0.32020956, -0.03444239],
         [-0.0284057 , -0.23952457,  0.14749175]],

        [[ 0.25230104,  0.22430933, -0.19253868],
         [-0.04161024, -0.32418028,  0.1732775 ]]],


       [[[-0.08000383,  0.26345772, -0.1671897 ],
         [ 0.02681547,  0.1905483 , -0.12523994]],

        [[ 0.20820308, -0.01917735,  0.20829588],
         [-0.21768038, -0.28715008,  0.1083397 ]],

        [[ 0.07176378, -0.26376104,  0.06171519],
         [ 0.3329991 ,  0.00463203, -0.33581996]]]], dtype=float32)]
(3, 3, 2, 3)
weights
[[ 1.  7. 13.]
 [19. 25. 31.]
 [37. 43.